routes/web.php
<?php

use App\Http\Controllers\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->get('/', function () {
    return view('dashboard');
});

Route::group(['prefix' => 'panel', 'middleware' => ['auth:sanctum', 'verified']], function () {
    Route::get('/new_page', [\App\Http\Controllers\PageController::class, 'create'])->name('newPage');
    Route::apiResource('/page', \App\Http\Controllers\PageController::class);

    Route::resource('/account', \App\Http\Controllers\AccountController::class);
    Route::resource('/category', \App\Http\Controllers\CategoryController::class);

    Route::resource('/data', \App\Http\Controllers\DataController::class);
    Route::post('/telegram', [\App\Http\Controllers\DataController::class, 'telegram'])->name('telegram');

    Route::group(['prefix' => 'user'], function () {
        Route::resource('admin', \App\Http\Controllers\AdminController::class);
        Route::resource('member', \App\Http\Controllers\MemberController::class);

        Route::resource('/roles', \App\Http\Controllers\RoleController::class);

        Route::get('/permissions', [\App\Http\Controllers\RoleController::class, 'permissionIndex']);
        Route::post('/permissions', [\App\Http\Controllers\RoleController::class, 'addPermission']);

        Route::post('/assign', [\App\Http\Controllers\RoleController::class, 'assignPermission']);
    });

});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/page/index.blade.php
@can('pages')
<style>
    .pg p {
        display: none;
    }
</style>
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <form class="form-inline m-3" action="{{route('page.index')}}">
                    <select class="browser-default custom-select px-3" name="category">
                        @foreach($categories as $key =>$category)
                            <option value="{{$key}}">{{$category}}</option>
                        @endforeach
                    </select>
                    <button type="submit" class="btn btn-primary mx-4">Filter</button>
                </form>
                <div class="w-full mx-auto">
                    <div class="bg-white shadow-md rounded my-6 mx-2">
                        <table class="text-left w-full border-collapse">
                            <!--Border collapse doesn't work on this site yet but it's available in newer tailwind versions -->
                            <thead>
                            <tr>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    id
                                </th>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    Name
                                </th>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    Category
                                </th>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    post_num
                                </th>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    followers
                                </th>

                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    Actions
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($pages as $page)
                                <tr class="hover:bg-grey-lighter">
                                    <td class="py-2 px-2 border-b border-grey-light">{{$page->id}}</td>
                                    <td class="py-2 px-2 border-b border-grey-light">{{$page->name}}</td>
                                    <td class="py-2 px-2 border-b border-grey-light">{{$page->category->name}}</td>
                                    <td class="py-2 px-2 border-b border-grey-light">{{$page->post_number}}</td>
                                    <td class="py-2 px-2 border-b border-grey-light">{{$page->followers}}</td>
                                    <td class="py-2 px-2 border-b border-grey-light">

                                        <form class="my-2" action="/panel/page/{{$page->id}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button
                                                class="text-gray-lighter font-bold py-1 px-3 rounded text-xs bg-red-100 hover:bg-blue-dark">
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="pg mx-auto w-1/3 m-3 justify-center">
                    {{$pages->render()}}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
@endcan

resources/views/page/new-page.blade.php
@can('pages')
    <x-app-layout>
        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                    <form class="text-center border border-light p-5 w-full sm:w-1/2 mx-auto"
                          action="{{route('page.store')}}" method="post">
                        @csrf

                        <p class="h4 mb-4">Create New Page</p>

                        <!-- Name -->
                        <input type="text" id="defaultContactFormName" class="form-control mb-4" placeholder="Name"
                               name="name">

                        <!-- Subject -->
                        <label>Category</label>
                        <select class="browser-default custom-select mb-4" name="category">
                            @foreach($categories as $key =>$category)
                                <option value="{{$key}}">{{$category}}</option>
                            @endforeach
                        </select>

                        <!-- Send button -->
                        <button class="btn btn-info btn-block" type="submit">Create</button>

                    </form>
                </div>
            </div>
        </div>
    </x-app-layout>
@endcan