routes/web.php
<?php

use App\Http\Controllers\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->get('/', function () {
    return view('dashboard');
});

Route::group(['prefix' => 'panel', 'middleware' => ['auth:sanctum', 'verified']], function () {
    Route::get('/new_page', [\App\Http\Controllers\PageController::class, 'create'])->name('newPage');
    Route::apiResource('/page', \App\Http\Controllers\PageController::class);

    Route::resource('/account', \App\Http\Controllers\AccountController::class);
    Route::resource('/category', \App\Http\Controllers\CategoryController::class);

    Route::resource('/data', \App\Http\Controllers\DataController::class);
    Route::post('/telegram', [\App\Http\Controllers\DataController::class, 'telegram'])->name('telegram');

    Route::group(['prefix' => 'user'], function () {
        Route::resource('admin', \App\Http\Controllers\AdminController::class);
        Route::resource('member', \App\Http\Controllers\MemberController::class);

        Route::resource('/roles', \App\Http\Controllers\RoleController::class);

        Route::get('/permissions', [\App\Http\Controllers\RoleController::class, 'permissionIndex']);
        Route::post('/permissions', [\App\Http\Controllers\RoleController::class, 'addPermission']);

        Route::post('/assign', [\App\Http\Controllers\RoleController::class, 'assignPermission']);
    });

});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Category.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Category
 *
 * @package App\Models
 *
 * @property int    $id
 *
 * @property string $name
 * @property int    $time_to_work
 *
 * @property Carbon $created_at
 * @property Carbon $updated_at
 */
class Category extends Model
{
    use HasFactory;

    protected $table = 'categories';

    protected $fillable = ['name', 'time_to_work'];

    // ------------------------------------ Relations ------------------------------------
    // ------------------------------------ Attributes ------------------------------------
    // ------------------------------------ Methods ------------------------------------

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::query()->paginate();

        return view('category.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|array
     */
    public function store(Request $request)
    {
        $attributes = $request->all();

        try {
            \DB::beginTransaction();
            $category = new Category();
            $category->fill($attributes);
            $category->save();

            \DB::commit();

            return redirect()->back();
        } catch (\Exception $ex) {
            \DB::rollBack();

            return [
                'success' => false,
                'message' => 'اشتباهی رخ داده است',
            ];
        }

    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Category $category
     *
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Category $category
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Category     $category
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Category $category
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->back();
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/category/index.blade.php
<style>
    .pg p {
        display: none;
    }
</style>
<x-app-layout>
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">

                <form class="text-center border border-light p-5 w-full sm:w-1/2 mx-auto"
                      action="{{route('category.store')}}" method="post">
                    @csrf

                    <p class="h4 mb-4">Create New Category</p>

                    <!-- Name -->
                    <input type="text" id="defaultContactFormName" class="form-control mb-4" placeholder="Name"
                           name="name">

                    <!-- password -->
                    <input type="text" id="defaultContactFormName" class="form-control mb-4" placeholder="timeToWork"
                           name="time_to_work">

                    <!-- Send button -->
                    <button class="btn btn-info btn-block" type="submit">Create</button>

                </form>

                <div class="w-full mx-auto">
                    <div class="bg-white shadow-md rounded my-6 mx-2">
                        <table class="text-left w-full border-collapse">
                            <!--Border collapse doesn't work on this site yet but it's available in newer tailwind versions -->
                            <thead>
                            <tr>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    id
                                </th>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    Name
                                </th>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    time to work
                                </th>
                                <th class="py-2 px-2 bg-grey-lightest font-bold uppercase text-sm text-grey-dark border-b border-grey-light">
                                    Action
                                </th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr class="hover:bg-grey-lighter">
                                    <td class="py-2 px-2 border-b border-grey-light">{{$category->id}}</td>
                                    <td class="py-2 px-2 border-b border-grey-light">{{$category->name}}</td>
                                    <td class="py-2 px-2 border-b border-grey-light">{{$category->time_to_work}}</td>
                                    <td class="py-2 px-2 border-b border-grey-light">

                                        <form class="my-2" action="/panel/category/{{$category->id}}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button
                                                class="text-gray-lighter font-bold py-1 px-3 rounded text-xs bg-red-100 hover:bg-blue-dark">
                                                Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="pg mx-auto w-1/3 m-3 justify-center">
                    {{$categories->render()}}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>