routes/web.php
<?php

use App\Http\Controllers\LoginController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->get('/', function () {
    return view('dashboard');
});

Route::group(['prefix' => 'panel', 'middleware' => ['auth:sanctum', 'verified']], function () {
    Route::get('/new_page', [\App\Http\Controllers\PageController::class, 'create'])->name('newPage');
    Route::apiResource('/page', \App\Http\Controllers\PageController::class);

    Route::resource('/account', \App\Http\Controllers\AccountController::class);
    Route::resource('/category', \App\Http\Controllers\CategoryController::class);

    Route::resource('/data', \App\Http\Controllers\DataController::class);
    Route::post('/telegram', [\App\Http\Controllers\DataController::class, 'telegram'])->name('telegram');

    Route::group(['prefix' => 'user'], function () {
        Route::resource('admin', \App\Http\Controllers\AdminController::class);
        Route::resource('member', \App\Http\Controllers\MemberController::class);

        Route::resource('/roles', \App\Http\Controllers\RoleController::class);

        Route::get('/permissions', [\App\Http\Controllers\RoleController::class, 'permissionIndex']);
        Route::post('/permissions', [\App\Http\Controllers\RoleController::class, 'addPermission']);

        Route::post('/assign', [\App\Http\Controllers\RoleController::class, 'assignPermission']);
    });

});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Http/Livewire/App.php
<?php

namespace App\Http\Livewire;

use App\Models\Category;
use App\Models\User;
use Livewire\Component;

class App extends Component
{
    public function render()
    {
        $categories = Category::all()->pluck('name', 'id');

        $kinds = User::KINDS;

        return view('livewire.app', ['categories' => $categories, 'kinds' => $kinds]);
    }
}

resources/views/livewire/app.blade.php
<div class="h-full">
    <!-- Sidebar -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3>Sidebar Menu</h3>
        </div>

        <ul class="list-unstyled components">
            <p class="text-center">دانالیزور</p>
            @can('pages')
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false"
                       class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="{{route('page.index')}}">Pages Index</a>
                        </li>
                        <li>
                            <a href="{{route('newPage')}}">New Page</a>
                        </li>
                        <li>
                            <a href="{{route('category.index')}}">Category</a>
                        </li>
                    </ul>
                </li>
            @endcan
            <li class="active">
                <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Instagram</a>
                <ul class="collapse list-unstyled" id="homeSubmenu">
                    @foreach($categories as $key => $category)
                        <li>
                            <a href="/panel/data?category={{$key}}&value={{$category}}">{{$category}}</a>
                        </li>
                    @endforeach
                </ul>
            </li>
            @can('users')

                <li class="active">
                    <a href="#userSubmenu" data-toggle="collapse" aria-expanded="false"
                       class="dropdown-toggle">Users</a>
                    <ul class="collapse list-unstyled" id="userSubmenu">
                        @foreach($kinds as $kind)
                            <li>
                                <a href="/panel/user/{{$kind}}">{{$kind}}</a>
                            </li>
                        @endforeach
                        <li>
                            <a href="/panel/user/permissions">Permissions</a>
                        </li>
                        <li>
                            <a href="/panel/user/roles">Roles</a>
                        </li>
                    </ul>
            @endcan
            @can('account')
                <li>
                    <a href="{{route('account.index')}}">Accounts</a>
                </li>
            @endcan
            <li class="active">
                <a href="#settingSubmenu" data-toggle="collapse" aria-expanded="false"
                   class="dropdown-toggle">Setting</a>
                <ul class="collapse list-unstyled" id="settingSubmenu">
                    @foreach($categories as $key => $category)
                        <li>
                            <a href="#">{{$category}}</a>
                        </li>
                    @endforeach
                </ul>

            <li>
                <a href="#">Contact</a>
            </li>
        </ul>
    </nav>
</div>